# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
use_frameworks!
use_modular_headers!
inhibit_all_warnings!

target 'MaskPlayer' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  # use_frameworks!

  # Pods for MaskPlayer
pod 'DKImagePickerController'

end
